image: iGLOO-be/docker-rvm-nvm

cache:
  paths:
    - node_modules
    - $HOME/.rvm
    - $HOME/.nvm

stages:
  - build
  - test
  - deploy

before_script:
  - npm i pm2 http-server contentascode/broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install

jekyll-build:
  stage: build
  script:
  - npm build

test-links:
  stage: test
  script:
  - npm test-links

deploy:
  script: 
  - npm run mirror

variables:
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: openintegrity
  CONFIG_REPO: openintegrity.org